# Generated by Django 3.1.4 on 2021-02-09 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(choices=[('True', 'True'), ('False', 'Flase'), ('Mostly true', 'Mostly true'), ('Mostly false', 'Mostly false')], max_length=256)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.game', verbose_name='related to Game')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to='score.player')),
                ('respoender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respoender', to='score.player')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='score.answer')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='score.game')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spørsmål', to='score.question')),
                ('questioner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_1', to='score.player')),
                ('respondent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_2', to='score.player')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.question', verbose_name='related to Question'),
        ),
    ]
